# -*- coding: utf-8 -*-
"""class5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMtMpvxfTxCBh6StMI7vVGDFeVOfjq86
"""

def atm():

    print("=================================")
    print("        ATM TRANSACTION          ")
    print("=================================")

    saved_pin = 1234
    balance = 5000

    pin = int(input("Enter your PIN: "))

    if pin == saved_pin:
        print("Login Successful")

        while True:
            print("\nChoose an option:")
            print("1. Check Balance")
            print("2. Withdraw Money")
            print("3. Deposit Money")
            print("4. Exit")

            choice = int(input("Enter your choice: "))

            if choice == 1:
                print("Your Balance:", balance)

            elif choice == 2:
                amount = int(input("Enter amount to withdraw: "))
                if amount <= balance:
                    balance = balance - amount
                    print("Withdrawal Successful")
                    print("Remaining Balance:", balance)
                else:
                    print("Insufficient Balance")

            elif choice == 3:
                amount = int(input("Enter amount to deposit: "))
                balance = balance + amount
                print("Deposit Successful")
                print("Updated Balance:", balance)

            elif choice == 4:
                print("Thank you for using ATM")
                break

            else:
                print("Invalid option")

    else:
        print("Invalid PIN")

atm()